apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-main-falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 7.0.0
    helm:
      values: |
        falco:
          jsonOutput: true
          jsonIncludeOutputProperty: true
          grpc:
            enabled: false
          grpcOutput:
            enabled: false
          tty: true
          collectors:
            enabled: true
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                    - fargate
          podSecurityContext: {}
          securityContext:
            privileged: true
        falcosidekick:
          enabled: true
          webui:
            enabled: false
          config:
            prometheus:
              enabled: true
          serviceMonitor:
            enabled: true
  destination:
    server: '{{ .Values.global.edgeApiUrl }}'
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
