apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-1-falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://falcosecurity.github.io/charts'
    chart: falco
    targetRevision: 4.10.0
    helm:
      values: |
        falco:
          jsonOutput: true
        
        #  노드 그룹 타겟팅을 위한 affinity 설정
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: eks.amazonaws.com/nodegroup
                  operator: In
                  values:
                  - his-main-ng-kafka
                  - his-main-vdi-node-group
        
        # Falco가 커널 이벤트를 감시하기 위한 필수 권한 (Privileged)
        securityContext:
          privileged: true

  destination:
    server: '{{ .Values.global.edgeApiUrl }}'
    namespace: security
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
