apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-1-monitoring-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 56.6.2
    helm:
      values: |
        grafana:
          enabled: false
        alertmanager:
          enabled: false

        # 노드 제약(Affinity)을 모두 제거하여 모든 노드에 배포되도록 수정
        prometheus-node-exporter:
          enabled: true
        kube-state-metrics:
          enabled: true
        prometheusOperator:
          enabled: true

        prometheus:
          enabled: true
          agentMode: true
          prometheusSpec:
            remoteWrite:
              - url: "http://prometheus.monitoring.local:9090/api/v1/write"
                # 🌟 데이터 전송 시 모든 메트릭에 'cluster: edge-1' 라벨을 추가
                writeRelabelConfigs:
                - targetLabel: cluster
                  replacement: edge-1
  destination:
    server: '{{ .Values.global.edgeApiUrl }}'
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
