# mysql.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: kafka # 아까 만든 kafka 구역을 같이 사용
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storageSize }}
  storageClassName: gp3 # gp3 스토리지 클래스 사용
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: kafka
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0 
        args: ["--default-time-zone=+09:00"]
        env:
        - name: TZ                             # 📍 [추가] 리눅스 컨테이너 시간을 서울로 변경
          value: "Asia/Seoul"
        - name: MYSQL_ROOT_PASSWORD
          #value: "1234" # 테스트용 루트 비밀번호 (원하는 대로 수정 가능)
          value: {{ .Values.mysql.rootPassword | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.databaseName | quote }}    # 자동으로 초기 생성될 데이터베이스 이름
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"  # 최소 512MB 메모리 확보
          limits:
            cpu: "500m"
            memory: "1Gi"    # t3.medium이 버틸 수 있도록 최대 1GB로 제한
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql # MySQL 데이터가 실제로 저장되는 경로
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc # 위에서 정의한 gp3 외장하드와 연결
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: kafka
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32399
  selector:
    app: mysql