apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-load-test-script
  namespace: dev-apps
data:
  test.js: |
    import http from 'k6/http';
    import { sleep, check } from 'k6';

    export const options = {
      stages: [
        { duration: '1m', target: 700 },   // 1분간 50 VU까지 증가
        { duration: '3m', target: 700 },   // 3분간 50 VU 유지
        { duration: '1m', target: 0 },    // 1분간 0으로 감소
      ],
    };

    export default function () {
      const res = http.get('http://hello-k3s-service.dev-apps.svc.cluster.local');
      check(res, {
        'status is 200': (r) => r.status === 200,
      });
      sleep(0.1);
    }
