# kubernetes/cicd/argocd/crd-installer.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-crd-installer
  namespace: argocd
  annotations:
    # `다른 앱보다 먼저 실행되어야 합니다.
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argo-cd'
    targetRevision: stable
    path: manifests/crds
  destination:
    # 엣지 클러스터로 배포
    server: '{{server}}' 
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
