# KEDA ScaledObject: app-service (test) 파드 스케일링
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-service-test-scaledobject
  namespace: web-apps-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-service
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 60
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "70"
