apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-smtp
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef: { name: aws-ssm, kind: ClusterSecretStore }
  target:
    name: grafana-smtp-secret
  data:
    - secretKey: GF_SMTP_PASSWORD
      remoteRef:
        key: /his-main/grafana/smtp-password
