apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-service-secret
  namespace: web-apps-test
spec:
  refreshInterval: 1h
  secretStoreRef: { name: aws-ssm, kind: ClusterSecretStore }
  target:
    name: app-service-secret
  dataFrom:
  - extract:
      key: /his-main/web-apps/app-service-secret
