apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: web-apps-test
spec:
  type: ClusterIP
  selector:
    app: app-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
