apiVersion: apps/v1
kind: Deployment
metadata:
  name: openemr
  namespace: his-emr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openemr
  template:
    metadata:
      labels:
        app: openemr
    spec:
      containers:
        - name: openemr
          image: 278584440977.dkr.ecr.ap-northeast-2.amazonaws.com/openemr:latest
          envFrom:
            - secretRef:
                name: openemr-db-secret
          ports:
            - containerPort: 80
          volumeMounts:
            - name: openemr-data
              mountPath: /var/www/localhost/htdocs/openemr/sites
            - name: php-config
              mountPath: /etc/php84/conf.d/openemr-custom.ini
              subPath: openemr-custom.ini
            - name: openemr-sqlconf
              mountPath: /var/www/localhost/htdocs/openemr/sites/default/sqlconf.php
              subPath: sqlconf.php
            - name: openemr-config
              mountPath: /var/www/localhost/htdocs/openemr/sites/default/config.php
              subPath: config.php
      volumes:
        - name: openemr-data
          persistentVolumeClaim:
            claimName: openemr-data
        - name: php-config
          configMap:
            name: openemr-php-config
        - name: openemr-sqlconf
          configMap:
            name: openemr-sqlconf
        - name: openemr-config
          configMap:
            name: openemr-config
