apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openemr-db-secret
  namespace: his-emr
spec:
  refreshInterval: 1h
  secretStoreRef: { name: aws-ssm, kind: ClusterSecretStore }
  target:
    name: openemr-db-secret
  dataFrom:
  - extract:
      key: /his-main/his-emr/openemr-db-secret
