apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openemr-data
  namespace: his-emr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
