apiVersion: v1
kind: ConfigMap
metadata:
  name: openemr-sqlconf
  namespace: his-emr
data:
  sqlconf.php: |
    <?php
    global $disable_utf8_flag;
    $disable_utf8_flag = false;
    $host   = getenv('SQL_HOST');
    $port   = getenv('SQL_PORT');
    $login  = getenv('SQL_LOGIN');
    $pass   = getenv('SQL_PASS');
    $dbase  = getenv('SQL_DBASE');
    $db_encoding = getenv('SQL_ENCODING');
    $sqlconf = [];
    global $sqlconf;
    $sqlconf['host']      = $host;
    $sqlconf['port']      = $port;
    $sqlconf['login']     = $login;
    $sqlconf['pass']      = $pass;
    $sqlconf['dbase']     = $dbase;
    $sqlconf['db_encoding'] = $db_encoding;
    $config = 1;
