apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k3s
  namespace: dev-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-k3s
  template:
    metadata:
      labels:
        app: hello-k3s
    spec:
      containers:
      - name: hpa-example
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "50Mi"
          limits:
            cpu: "500m"
            memory: "100Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 3  

