# clusters/hub/apps/templates/app-service-test-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-service-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '{{ .Values.global.gitlabUrl }}/root/gitops-repo.git'
    path: kubernetes/apps/app-service-test
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: web-apps-test
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:    
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
