apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/autoscaler'
    chart: cluster-autoscaler
    targetRevision: 9.37.0
    helm:
      values: |
        autoDiscovery:
          clusterName: his-main  # 실제 EKS 클러스터 이름으로 변경
        awsRegion: ap-northeast-2
        # CA는 infra 노드에 배치
        nodeSelector:
          role: infra
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "infra"
            effect: "NoSchedule"
        rbac:
          serviceAccount:
            annotations:
              # IRSA: CA가 ASG를 제어할 수 있는 IAM Role ARN으로 변경
              eks.amazonaws.com/role-arn: "arn:aws:iam::278584440977:role/his-main-cluster-autoscaler-role"
        extraArgs:
          # his-main-ng-service 노드그룹만 스케일링 대상으로 지정
          node-group-auto-discovery: "asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/his-main"
          scale-down-enabled: "true"
          scale-down-delay-after-add: "2m"
          scale-down-unneeded-time: "5m"
          skip-nodes-with-system-pods: "false"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

