apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/external-dns/'
    chart: external-dns
    targetRevision: 1.14.3
    helm:
      values: |
        provider: aws
        aws:
          zoneType: private
        #  도메인 필터는 여기에
        domainFilters:
          - monitoring.local
        
        serviceAccount:
          create: true
          name: external-dns
          # 어노테이션은 여기서 빼고, 파드 내부 환경변수로 제어 (ESO 방식)
        
        #  정책 및 등록 방식은 values 안에 명시 (extraArgs 충돌 방지)
        policy: upsert-only
        registry: txt
        txtOwnerId: my-cluster-id
        sources:
          - service
          - ingress

        #  우리가 약속한 시크릿 참조 (ESO 방식)
        extraEnv:
          - name: AWS_ROLE_ARN
            valueFrom:
              secretKeyRef:
                name: external-dns-secret-k8s
                key: role-arn

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
