apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/external-dns/'
    chart: external-dns
    targetRevision: 1.14.3
    helm:
      values: |
        provider: aws
        aws:
          zoneType: private
        domainFilters:
          - monitoring.local
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            # IAM Role ARN (SSM에서 관리 중인 Role을 사용)
            eks.amazonaws.com/role-arn: "arn:aws:iam::278584440977:role/ExternalDNS-Role"
        #  파드 보안 설정 최적화
        podAnnotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::278584440977:role/ExternalDNS-Role"
        # ExternalDNS가 도메인을 더 잘 찾도록 추가 옵션
        extraArgs:
          - --policy=upsert-only
          - --registry=txt
          - --txt-owner-id=my-cluster-id
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
