# kubernetes/infrastructure/falco-stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://falcosecurity.github.io/charts'
    chart: falco
    targetRevision: 4.10.0
    helm:
      values: |
        falco:
          jsonOutput: true
        
        # affinity는 falco 블록에서 빼내고, Pod 레벨의 설정을 지원하는 
        # 차트의 표준 필드인 nodeSelector를 사용합니다.
        nodeSelector:
          eks.amazonaws.com/compute-type: ec2

        # 보안 모듈이 커널에 접근하기 위한 필수 권한
        securityContext:
          privileged: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
