# kubernetes/infrastructure/falco-stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://falcosecurity.github.io/charts'
    chart: falco
    targetRevision: 4.10.0
    helm:
      values: |
        falco:
          jsonOutput: true
        
        # Fargate를 제외하고, Falco가 정상 작동할 수 있는 infra 노드로 고정
        nodeSelector:
          role: infra

        # 보안 모듈이 커널에 접근하기 위한 필수 권한
        securityContext:
          privileged: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
