apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 7.0.0
    helm:
      values: |
        falco:
          jsonOutput: true
          jsonIncludeOutputProperty: true
          grpc:
            enabled: false
          grpcOutput:
            enabled: false
          tty: true
          collectors:
            enabled: true
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                    - fargate
          podSecurityContext: {}
          securityContext:
            privileged: true

        falcosidekick:
          enabled: true
          config:
            prometheus:
              enabled: true
            kafka:
              hostport: "a587fce1a18e44dddb5113906ef93591-dbe568beb162965a.elb.ap-northeast-2.amazonaws.com:9092"
              topic: "falco-devops"
          serviceMonitor:
            enabled: true
          webui:
            enabled: true
            redis:
              storageEnabled: false
            service:
              type: ClusterIP

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
