apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # 모니터링 스택 설치 이후에 안전하게 생성되도록 순서 부여
spec:
  project: default
  source:
    repoURL: '{{ .Values.global.gitlabUrl }}/root/gitops-repo.git'
    path: kubernetes/cicd/monitoring
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
