apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-build-agent
  namespace: jenkins-build
  annotations:
    
    eks.amazonaws.com/role-arn: "arn:aws:iam::278584440977:role/his-main-jenkins-agent-role"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-build-agent-admin-binding
subjects:
- kind: ServiceAccount
  name: jenkins-build-agent
  namespace: jenkins-build
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
