apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-infra-config
  namespace: jenkins
data:
  GITLAB_URL: "http://10.0.4.10:8080"
  GITLAB_USER: "root"
  JENKINS_IP: "jenkins-stack.jenkins.svc.cluster.local"
  JENKINS_PORT: "8080"
  TARGET_NS: "dev-apps"
  MONITOR_NS: "monitoring"

---
#  jenkins-build 네임스페이스용 ConfigMap 선언
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-infra-config
  namespace: jenkins-build
data:
  GITLAB_URL: "http://10.0.4.10:8080"
  GITLAB_USER: "root"
  JENKINS_IP: "jenkins-stack.jenkins.svc.cluster.local"
  JENKINS_PORT: "8080"
  TARGET_NS: "dev-apps"
  MONITOR_NS: "monitoring"
