apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef: { name: aws-ssm, kind: ClusterSecretStore }
  target:
    name: jenkins-stack
  data:
    - secretKey: jenkins-admin-user
      remoteRef:
        key: /his-main/jenkins/admin-user
    - secretKey: jenkins-admin-password
      remoteRef:
        key: /his-main/jenkins/admin-password
