apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-infra-config
  namespace: jenkins
data:
  # 🌟 GitLab 정보 (IP 하드코딩 제거 -> EKS 내부 DNS 주소 사용)
  GITLAB_URL: "http://gitlab-service.jenkins.svc.cluster.local"
  GITLAB_USER: "root"
  # Jenkins 정보 
  JENKINS_IP: "jenkins.jenkins.svc.cluster.local" 
  JENKINS_PORT: "8080"
  # 배포 타겟 정보
  TARGET_NS: "dev-apps"
  MONITOR_NS: "monitoring"
