apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdi-internal-service
  namespace: vdi-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vdi-internal-service
  template:
    metadata:
      labels:
        app: vdi-internal-service
    spec:
      containers:
      - name: vdi-internal-service
        image: 278584440977.dkr.ecr.ap-northeast-2.amazonaws.com/vdi-service/app-image:placeholder
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
