apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-vdi-falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 7.0.0
    helm:
      values: |
        image:
          registry: 278584440977.dkr.ecr.ap-northeast-2.amazonaws.com
          repository: vdi/pod-image
          tag: falco-0.42.0
        driver:
          loader:
            initContainer:
              image:
                registry: 278584440977.dkr.ecr.ap-northeast-2.amazonaws.com
                repository: vdi/pod-image
                tag: falco-driver-loader-0.42.0
        falcoctl:
          image:
            registry: 278584440977.dkr.ecr.ap-northeast-2.amazonaws.com
            repository: vdi/pod-image
            tag: falcoctl-0.11.4
          artifact:
            install:
              enabled: false
            follow:
              enabled: false
        falco:
          jsonOutput: true
          jsonIncludeOutputProperty: true
          grpc:
            enabled: false
          grpcOutput:
            enabled: false
          tty: true
          collectors:
            enabled: true
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                    - fargate
          podSecurityContext: {}
          securityContext:
            privileged: true
        falcosidekick:
          enabled: true
          image:
            registry: 278584440977.dkr.ecr.ap-northeast-2.amazonaws.com
            repository: vdi/pod-image
            tag: falcosidekick-2.31.0
          webui:
            enabled: false
          config:
            prometheus:
              enabled: true
          serviceMonitor:
            enabled: true
  destination:
    server: '{{ .Values.global.edgeApiUrl }}'
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
