apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-2-monitoring-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 56.6.2
    helm:
      values: |
        grafana: { enabled: false }
        alertmanager: { enabled: false }
        prometheus-node-exporter:
          enabled: true
          affinity: &global-affinity
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values: [fargate]
        kube-state-metrics:
          enabled: true
          affinity: *global-affinity
        prometheusOperator:
          enabled: true
          affinity: *global-affinity
        prometheus:
          enabled: true
          agentMode: true
          prometheusSpec:
            affinity: *global-affinity
            remoteWrite:
              - url: "http://prometheus:9090/api/v1/write"
  destination:
    server: '{{ .Values.global.edgeApiUrl }}'
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
