apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-service-ingress
  namespace: web-apps
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # Name 태그 기반 서브넷 명시 지정 (클러스터 재생성 대응)
    alb.ingress.kubernetes.io/subnets: his-main-public-a, his-main-public-c
    # HTTPS 활성화 + HTTP→HTTPS 리다이렉트
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'

    # ExternalDNS(퍼블릭 존 담당 인스턴스)가 이 host를 보고
    # Route53 퍼블릭 호스티드존에 자동으로 A(Alias) 레코드를 생성/관리함
    external-dns.alpha.kubernetes.io/hostname: "armymedicalcenter.click"
spec:
  ingressClassName: alb
  tls:
  - hosts:
    - "armymedicalcenter.click"
  rules:
  - host: "armymedicalcenter.click"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service   # Rollout의 stableService와 일치해야 함
            port:
              name: use-annotation
